# Generated by Django 3.2.18 on 2023-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='country',
            field=models.CharField(default='Türkiye', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Sepet'), ('pending', 'Ödeme Bekleniyor'), ('shipped', 'Kargoya Verildi'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], max_length=20),
        ),
    ]
